# Generated by Django 3.1.7 on 2021-04-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_aboutpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
